version: "2"

run:
  timeout: 5m

formatters:
  enable:
    - gofumpt

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive
    - misspell
    - unconvert
    - unparam

issues:
  exclude-use-default: false
